language: python
sudo: false
virtualenv:
  system_site_packages: true
python:
  - "3.6"
env:
  - DJANGO="Django>=1.11.0,<1.12.0"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
